baseURL = 'https://alessiocassieri.netlify.app/'
languageCode = 'en-us'
title = 'Alessio Cassieri'
theme = 'gokarna'

defaultContentLanguage = "en"
[languages]
  [languages.en]
    languageName = "English"
    weight = 1
  [languages.it]
    languageName = "Italiano"
    weight = 2


# Automatically generate robots.txt
enableRobotsTXT = true

#Emoji
enableEmoji = true

[menu]
  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "projects"
    url = "/projects/"
    pre = "<span data-feather='code'></span>"
    # Display name
    name = "Projects"
    # Weights are used to determine the ordering
    weight = 1
    
  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "posts"
    url = "/posts/"
    pre = "<span data-feather='book'></span>"
    # Display name
    name = "Posts"
    # Weights are used to determine the ordering
    weight = 2
    
  [[menu.main]]
    identifier = "experience"
    name = "Experience"
    url = "/experience/"
    weight = 3
    pre = "<span data-feather='briefcase'></span>"
    
  [[menu.main]]
    identifier = "technologies"
    name = "Technologies"
    url = "/technologies/"
    weight = 4
    pre = "<span data-feather='terminal'></span>"

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 5
    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='link'></span>"
  
  #  [[menu.main]]
  #    identifier = "tags"
  #    name = "Tags"
  #    url = "/tags/"
  #    weight = 6
  #    pre = "<span data-feather='tag'></span>"
[params]
  # URL for the avatar on homepage
  avatarURL = "/images/pic.png"

  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = "size-s"

  # Description to display on homepage
  description = "Sky's the Limit!"

  # Accent color is displayed when you hover over <a> tags
  accentColor = "#ff79c6"

  # Display "back to top" button on posts
  ShowBackToTopButton = true
  socialIcons = [
    {name = "linkedin", url = "https://www.linkedin.com/in/alessio-cassieri/"}, 
    {name = "github", url = "https://github.com/Cassio7"},
    {name = "spotify", url = "https://open.spotify.com/user/21qfkrxjcoiicqxb6vi5ayi5y?si=d312528bc96f4a12"},
    {name = "email", url = "mailto:alessio.cassieri@protonmail.com"}
  ]