baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Alessio Cassieri'
theme = 'gokarna'

# Automatically generate robots.txt
enableRobotsTXT = true

[menu]
  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "projects"

    url = "/projects/"
    
    pre = "<span data-feather='code'></span>"


    # Display name
    name = "Projects"

    # Weights are used to determine the ordering
    weight = 1
    
  [[menu.main]]
    identifier = "experience"
    name = "Experience"
    url = "/experience/"
    weight = 2
    pre = "<span data-feather='briefcase'></span>"
    

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3
    pre = "<span data-feather='tag'></span>"
  
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4
    
    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='smile'></span>"

[params]
  # URL for the avatar on homepage
  avatarURL = "/images/pic.png"

  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = "size-s"

  # Description to display on homepage
  description = "Welcome to my web portfolio!"

  # Accent color is displayed when you hover over <a> tags
  accentColor = "#ff5555"

  # Display "back to top" button on posts
  ShowBackToTopButton = true
